spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partner_matching?serverTimezone=GMT%2b8
    username: root
    password: 123456
  # session 超时时间
  session:
    timeout: 86400
    redis:
      flush-mode: on_save
      namespace: "lingxi:session"
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8081

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  default-flat-param-object: true
